<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\framework\ClayMo.Framework.Authorization\ClayMo.Framework.Authorization.csproj" />
      <ProjectReference Include="..\..\framework\ClayMo.Framework.Core\ClayMo.Framework.Core.csproj" />
      <ProjectReference Include="..\..\modules\auditlogging\ClayMo.Module.AuditLogging.SqlSugar\ClayMo.Module.AuditLogging.SqlSugar.csproj" />
      <ProjectReference Include="..\..\modules\identity\ClayMo.Module.Identity.SqlSugar\ClayMo.Module.Identity.SqlSugar.csproj" />
      <ProjectReference Include="..\..\modules\identity\ClayMo.Module.Identity\ClayMo.Module.Identity.SqlSugar\ClayMo.Module.Identity.SqlSugar.csproj" />
      <ProjectReference Include="..\..\framework\ClayMo.Framework.SqlSugar\ClayMo.Framework.SqlSugar.csproj" />
      <ProjectReference Include="..\..\modules\auditlogging\ClayMo.Module.AuditLogging\ClayMo.Module.AuditLogging.SqlSugar\ClayMo.Module.AuditLogging.SqlSugar.csproj" />
      <ProjectReference Include="..\..\modules\tenantmanagement\ClayMo.Module.TenantManagement.SqlSugar\ClayMo.Module.TenantManagement.SqlSugar.csproj" />
      <ProjectReference Include="..\..\modules\kb\ClayMo.Module.Knowledge.SqlSugar\ClayMo.Module.Knowledge.SqlSugar.csproj" />
      <ProjectReference Include="..\..\modules\workspace\ClayMo.Module.Workspace.SqlSugar\ClayMo.Module.Workspace.SqlSugar.csproj" />
      <ProjectReference Include="..\ClayMo.Abp.Domain\ClayMo.Abp.Domain.csproj" />
    </ItemGroup>

</Project>
