<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="SqlSugarCore" Version="5.1.4.208-preview26" />
      <PackageReference Include="Volo.Abp.Ddd.Domain" Version="10.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\framework\ClayMo.Framework.SqlSugar.Abstractions\ClayMo.Framework.SqlSugar.Abstractions.csproj" />
      <ProjectReference Include="..\ClayMo.Module.Workspace.Domain.Shared\ClayMo.Module.Workspace.Domain.Shared.csproj" />
    </ItemGroup>

</Project>
