// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	files "file-service/internal/handler/files"
	"file-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtUserContext},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/files",
					Handler: files.ListFilesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/files/:fileId",
					Handler: files.GetFileHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/files/:fileId",
					Handler: files.DeleteFileHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/uploads/sessions",
					Handler: files.CreateUploadSessionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/uploads/sessions/:sessionId/abort",
					Handler: files.AbortUploadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/uploads/sessions/:sessionId/complete",
					Handler: files.CompleteUploadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/uploads/sessions/:sessionId/finalize",
					Handler: files.FinalizeUploadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/uploads/sessions/:sessionId/parts/presign",
					Handler: files.PresignPartsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/uploads/sessions/:sessionId/progress",
					Handler: files.UploadProgressHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/fs"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtUserContext},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/files/:fileId/content",
					Handler: files.GetFileContentHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/fs"),
	)
}
