// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AbortUploadRequest struct {
	SessionId string `path:"sessionId"`
}

type AbortUploadResponse struct {
	SessionId string `json:"sessionId"`
	Success   bool   `json:"success"`
	Message   string `json:"message,omitempty"`
}

type CompleteUploadRequest struct {
	SessionId string           `path:"sessionId"`
	Parts     []UploadPartInfo `json:"parts,omitempty"` // multipart mode (required)
}

type CompleteUploadResponse struct {
	SessionId string `json:"sessionId"`
	Status    string `json:"status"` // Completed
	Message   string `json:"message,omitempty"`
}

type CreateUploadSessionRequest struct {
	IdempotencyKey     string `json:"idempotencyKey,omitempty"` // 幂等 key（前端生成 UUID）
	FileName           string `json:"fileName"`
	FileSize           int64  `json:"fileSize"`
	FileType           string `json:"fileType,omitempty"`
	BizType            string `json:"bizType,omitempty"`
	FileHash           string `json:"fileHash,omitempty"`
	Mode               string `json:"mode,omitempty"` // auto|single|multipart
	PreferredChunkSize int64  `json:"preferredChunkSize,omitempty"`
}

type CreateUploadSessionResponse struct {
	SessionId  string            `json:"sessionId,omitempty"`
	Mode       string            `json:"mode,omitempty"`
	ObjectKey  string            `json:"objectKey,omitempty"`
	UploadUrl  string            `json:"uploadUrl,omitempty"`  // single mode
	Headers    map[string]string `json:"headers,omitempty"`    // single mode
	UploadId   string            `json:"uploadId,omitempty"`   // multipart mode
	ChunkSize  int64             `json:"chunkSize,omitempty"`  // multipart mode
	TotalParts int               `json:"totalParts,omitempty"` // multipart mode
	ExpiresAt  int64             `json:"expiresAt,omitempty"`  // Unix seconds
	HitType    string            `json:"hitType,omitempty"`    // none|idempotent|dedup
	FileId     string            `json:"fileId,omitempty"`     // only when dedup hit
	Status     string            `json:"status,omitempty"`     // Initiated|Uploading|Completed|Aborted|Expired|Failed
	Message    string            `json:"message,omitempty"`
}

type DeleteFileRequest struct {
	FileId string `path:"fileId"`
	Hard   bool   `form:"hard,optional"`
}

type DeleteFileResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message,omitempty"`
}

type FileItem struct {
	FileId     string `json:"fileId"`
	FileName   string `json:"fileName"`
	FileSize   int64  `json:"fileSize"`
	FileType   string `json:"fileType"`
	BizType    string `json:"bizType"`
	FileHash   string `json:"fileHash"`
	Status     string `json:"status"`
	Width      int    `json:"width,omitempty"`
	Height     int    `json:"height,omitempty"`
	DurationMs int64  `json:"durationMs,omitempty"`
	CreatedAt  int64  `json:"createdAt"`
	UpdatedAt  int64  `json:"updatedAt"`
}

type FinalizeUploadRequest struct {
	SessionId string `path:"sessionId"`
}

type FinalizeUploadResponse struct {
	FileId   string `json:"fileId"`
	Status   string `json:"status"` // Available
	FileType string `json:"fileType"`
	FileSize int64  `json:"fileSize"`
	Message  string `json:"message,omitempty"`
}

type GetFileContentRequest struct {
	FileId      string `path:"fileId"`
	Disposition string `form:"disposition,optional"` // inline|attachment, default: inline
	Variant     string `form:"variant,optional"`     // 预留：origin|thumb_300w|...
	W           int    `form:"w,optional"`           // 预留：图片宽度
	H           int    `form:"h,optional"`           // 预留：图片高度
	Q           int    `form:"q,optional"`           // 预留：图片质量
}

type GetFileRequest struct {
	FileId string `path:"fileId"`
}

type GetFileResponse struct {
	FileItem
}

type ListFilesRequest struct {
	PageRequest
	BizType     string `form:"bizType,optional"`
	Keyword     string `form:"keyword,optional"`
	Status      string `form:"status,optional"`
	Mime        string `form:"mime,optional"`
	OwnerId     string `form:"ownerId,optional"`
	CreatedFrom string `form:"createdFrom,optional"`
	CreatedTo   string `form:"createdTo,optional"`
}

type ListFilesResponse struct {
	PageResponse
	Items []FileItem `json:"items"`
}

type PageRequest struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"pageSize,default=20"`
}

type PageResponse struct {
	Page     int `json:"page"`
	PageSize int `json:"pageSize"`
	Total    int `json:"total"`
}

type PresignPartsRequest struct {
	SessionId   string `path:"sessionId"`
	PartNumbers []int  `json:"parts"` // e.g. [1,2,3,4,5]
}

type PresignPartsResponse struct {
	Parts []PresignedPart `json:"parts"`
}

type PresignedPart struct {
	PartNumber int               `json:"partNumber"`
	UploadUrl  string            `json:"uploadUrl"`
	Headers    map[string]string `json:"headers,omitempty"`
	ExpiresAt  int64             `json:"expiresAt"` // Unix seconds
}

type UploadPartInfo struct {
	PartNumber int    `json:"partNumber"`
	ETag       string `json:"etag"`
}

type UploadProgressRequest struct {
	SessionId string `path:"sessionId"`
}

type UploadProgressResponse struct {
	SessionId     string `json:"sessionId"`
	Mode          string `json:"mode"`
	Status        string `json:"status"`
	UploadedParts []int  `json:"uploadedParts,omitempty"`
	TotalParts    int    `json:"totalParts,omitempty"`
	Progress      int    `json:"progress,omitempty"`
}
