<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\framework\ClayMo.Framework.SqlSugar.Abstractions\ClayMo.Framework.SqlSugar.Abstractions.csproj" />
      <ProjectReference Include="..\..\..\framework\ClayMo.Framework.Identity\ClayMo.Framework.Identity.Domain\ClayMo.Framework.Identity.Domain.csproj" />
      <ProjectReference Include="..\..\..\framework\ClayMo.Framework.SqlSugar\ClayMo.Framework.SqlSugar.csproj" />
      <ProjectReference Include="..\..\identity\ClayMo.Module.Identity.Domain.Shared\ClayMo.Module.Identity.Domain.Shared.csproj" />
      <ProjectReference Include="..\..\identity\ClayMo.Module.Identity.Domain\ClayMo.Module.Identity.Domain.csproj" />
      <ProjectReference Include="..\ClayMo.Module.Kb.Domain\ClayMo.Module.Kb.Domain.csproj" />
      <ProjectReference Include="..\ClayMo.Module.Knowledge.Domain.Shared\ClayMo.Module.Knowledge.Domain.Shared.csproj" />
      <ProjectReference Include="..\ClayMo.Module.Knowledge.Domain\ClayMo.Module.Knowledge.Domain.csproj" />
    </ItemGroup>

</Project>
