// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	fileInfosFieldNames          = builder.RawFieldNames(&FileInfos{})
	fileInfosRows                = strings.Join(fileInfosFieldNames, ",")
	fileInfosRowsExpectAutoSet   = strings.Join(stringx.Remove(fileInfosFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	fileInfosRowsWithPlaceHolder = strings.Join(stringx.Remove(fileInfosFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	fileInfosModel interface {
		Insert(ctx context.Context, data *FileInfos) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*FileInfos, error)
		FindOneByFileId(ctx context.Context, fileId string) (*FileInfos, error)
		Update(ctx context.Context, data *FileInfos) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultFileInfosModel struct {
		conn  sqlx.SqlConn
		table string
	}

	FileInfos struct {
		Id         uint64 `db:"id"`          // PK
		FileId     string `db:"file_id"`     // business id (uuid)
		TenantId   string `db:"tenant_id"`   // tenant id
		OwnerId    string `db:"owner_id"`    // owner user id
		FileName   string `db:"file_name"`   // original filename
		FileSize   int64  `db:"file_size"`   // bytes
		FileType   string `db:"file_type"`   // mime
		BizType    string `db:"biz_type"`    // business category
		FileHash   string `db:"file_hash"`   // sha256/md5 (optional)
		Bucket     string `db:"bucket"`      // storage bucket
		ObjectKey  string `db:"object_key"`  // storage object key
		Status     string `db:"status"`      // Uploading|Available|Processing|Failed|Deleted|Aborted
		Width      int64  `db:"width"`       // image width
		Height     int64  `db:"height"`      // image height
		DurationMs int64  `db:"duration_ms"` // audio/video duration ms
		Version    int64  `db:"version"`     // optimistic lock version
		CreatedAt  int64  `db:"created_at"`  // unix ms
		UpdatedAt  int64  `db:"updated_at"`  // unix ms
		DeletedAt  int64  `db:"deleted_at"`  // unix ms, 0=not deleted
	}
)

func newFileInfosModel(conn sqlx.SqlConn) *defaultFileInfosModel {
	return &defaultFileInfosModel{
		conn:  conn,
		table: "`file_infos`",
	}
}

func (m *defaultFileInfosModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultFileInfosModel) FindOne(ctx context.Context, id uint64) (*FileInfos, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", fileInfosRows, m.table)
	var resp FileInfos
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFileInfosModel) FindOneByFileId(ctx context.Context, fileId string) (*FileInfos, error) {
	var resp FileInfos
	query := fmt.Sprintf("select %s from %s where `file_id` = ? limit 1", fileInfosRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, fileId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFileInfosModel) Insert(ctx context.Context, data *FileInfos) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, fileInfosRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.FileId, data.TenantId, data.OwnerId, data.FileName, data.FileSize, data.FileType, data.BizType, data.FileHash, data.Bucket, data.ObjectKey, data.Status, data.Width, data.Height, data.DurationMs, data.Version, data.DeletedAt)
	return ret, err
}

func (m *defaultFileInfosModel) Update(ctx context.Context, newData *FileInfos) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, fileInfosRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.FileId, newData.TenantId, newData.OwnerId, newData.FileName, newData.FileSize, newData.FileType, newData.BizType, newData.FileHash, newData.Bucket, newData.ObjectKey, newData.Status, newData.Width, newData.Height, newData.DurationMs, newData.Version, newData.DeletedAt, newData.Id)
	return err
}

func (m *defaultFileInfosModel) tableName() string {
	return m.table
}
