// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	fileOutboxFieldNames          = builder.RawFieldNames(&FileOutbox{})
	fileOutboxRows                = strings.Join(fileOutboxFieldNames, ",")
	fileOutboxRowsExpectAutoSet   = strings.Join(stringx.Remove(fileOutboxFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	fileOutboxRowsWithPlaceHolder = strings.Join(stringx.Remove(fileOutboxFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	fileOutboxModel interface {
		Insert(ctx context.Context, data *FileOutbox) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*FileOutbox, error)
		FindOneByEventId(ctx context.Context, eventId string) (*FileOutbox, error)
		Update(ctx context.Context, data *FileOutbox) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultFileOutboxModel struct {
		conn  sqlx.SqlConn
		table string
	}

	FileOutbox struct {
		Id            uint64         `db:"id"`             // PK
		EventId       string         `db:"event_id"`       // event id (uuid)
		TenantId      string         `db:"tenant_id"`      // tenant id
		AggregateType string         `db:"aggregate_type"` // file|transcode|...
		AggregateId   string         `db:"aggregate_id"`   // e.g. fileId/taskId
		EventType     string         `db:"event_type"`     // e.g. FileUploaded, TranscodeQueued
		Payload       string         `db:"payload"`        // json payload
		Headers       sql.NullString `db:"headers"`        // json headers (optional)
		Status        string         `db:"status"`         // Pending|Published|Failed
		RetryCount    int64          `db:"retry_count"`
		NextRetryAt   int64          `db:"next_retry_at"` // unix ms, 0=immediately
		LastError     sql.NullString `db:"last_error"`
		CreatedAt     int64          `db:"created_at"` // unix ms
		UpdatedAt     int64          `db:"updated_at"` // unix ms
	}
)

func newFileOutboxModel(conn sqlx.SqlConn) *defaultFileOutboxModel {
	return &defaultFileOutboxModel{
		conn:  conn,
		table: "`file_outbox`",
	}
}

func (m *defaultFileOutboxModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultFileOutboxModel) FindOne(ctx context.Context, id uint64) (*FileOutbox, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", fileOutboxRows, m.table)
	var resp FileOutbox
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFileOutboxModel) FindOneByEventId(ctx context.Context, eventId string) (*FileOutbox, error) {
	var resp FileOutbox
	query := fmt.Sprintf("select %s from %s where `event_id` = ? limit 1", fileOutboxRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, eventId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFileOutboxModel) Insert(ctx context.Context, data *FileOutbox) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, fileOutboxRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.EventId, data.TenantId, data.AggregateType, data.AggregateId, data.EventType, data.Payload, data.Headers, data.Status, data.RetryCount, data.NextRetryAt, data.LastError)
	return ret, err
}

func (m *defaultFileOutboxModel) Update(ctx context.Context, newData *FileOutbox) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, fileOutboxRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.EventId, newData.TenantId, newData.AggregateType, newData.AggregateId, newData.EventType, newData.Payload, newData.Headers, newData.Status, newData.RetryCount, newData.NextRetryAt, newData.LastError, newData.Id)
	return err
}

func (m *defaultFileOutboxModel) tableName() string {
	return m.table
}
