// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	uploadSessionsFieldNames          = builder.RawFieldNames(&UploadSessions{})
	uploadSessionsRows                = strings.Join(uploadSessionsFieldNames, ",")
	uploadSessionsRowsExpectAutoSet   = strings.Join(stringx.Remove(uploadSessionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	uploadSessionsRowsWithPlaceHolder = strings.Join(stringx.Remove(uploadSessionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	uploadSessionsModel interface {
		Insert(ctx context.Context, data *UploadSessions) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UploadSessions, error)
		FindOneBySessionId(ctx context.Context, sessionId string) (*UploadSessions, error)
		FindOneByTenantIdIdempotencyKey(ctx context.Context, tenantId string, idempotencyKey string) (*UploadSessions, error)
		Update(ctx context.Context, data *UploadSessions) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUploadSessionsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UploadSessions struct {
		Id              uint64 `db:"id"`                // PK
		SessionId       string `db:"session_id"`        // session id (uuid, 前缀 us_)
		TenantId        string `db:"tenant_id"`         // tenant id
		OwnerId         string `db:"owner_id"`          // owner user id
		IdempotencyKey  string `db:"idempotency_key"`   // client-generated idempotency key
		FileName        string `db:"file_name"`         // original filename
		FileSize        int64  `db:"file_size"`         // bytes
		FileType        string `db:"file_type"`         // mime
		BizType         string `db:"biz_type"`          // business category
		FileHash        string `db:"file_hash"`         // sha256/md5 (optional, dedup)
		Bucket          string `db:"bucket"`            // storage bucket
		ObjectKey       string `db:"object_key"`        // storage object key (unique per session)
		Mode            string `db:"mode"`              // single|multipart
		UploadId        string `db:"upload_id"`         // multipart uploadId from storage
		ChunkSize       int64  `db:"chunk_size"`        // multipart chunk size bytes
		TotalParts      int64  `db:"total_parts"`       // multipart total parts
		Status          string `db:"status"`            // session status
		FinalizedFileId string `db:"finalized_file_id"` // fileId after finalize (for idempotency)
		FinalizedAt     int64  `db:"finalized_at"`      // unix ms, 0=not finalized
		ExpiresAt       int64  `db:"expires_at"`        // unix ms
		CreatedAt       int64  `db:"created_at"`        // unix ms
		UpdatedAt       int64  `db:"updated_at"`        // unix ms
	}
)

func newUploadSessionsModel(conn sqlx.SqlConn) *defaultUploadSessionsModel {
	return &defaultUploadSessionsModel{
		conn:  conn,
		table: "`upload_sessions`",
	}
}

func (m *defaultUploadSessionsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUploadSessionsModel) FindOne(ctx context.Context, id uint64) (*UploadSessions, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", uploadSessionsRows, m.table)
	var resp UploadSessions
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUploadSessionsModel) FindOneBySessionId(ctx context.Context, sessionId string) (*UploadSessions, error) {
	var resp UploadSessions
	query := fmt.Sprintf("select %s from %s where `session_id` = ? limit 1", uploadSessionsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, sessionId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUploadSessionsModel) FindOneByTenantIdIdempotencyKey(ctx context.Context, tenantId string, idempotencyKey string) (*UploadSessions, error) {
	var resp UploadSessions
	query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `idempotency_key` = ? limit 1", uploadSessionsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, tenantId, idempotencyKey)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUploadSessionsModel) Insert(ctx context.Context, data *UploadSessions) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, uploadSessionsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.SessionId, data.TenantId, data.OwnerId, data.IdempotencyKey, data.FileName, data.FileSize, data.FileType, data.BizType, data.FileHash, data.Bucket, data.ObjectKey, data.Mode, data.UploadId, data.ChunkSize, data.TotalParts, data.Status, data.FinalizedFileId, data.FinalizedAt, data.ExpiresAt)
	return ret, err
}

func (m *defaultUploadSessionsModel) Update(ctx context.Context, newData *UploadSessions) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, uploadSessionsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.SessionId, newData.TenantId, newData.OwnerId, newData.IdempotencyKey, newData.FileName, newData.FileSize, newData.FileType, newData.BizType, newData.FileHash, newData.Bucket, newData.ObjectKey, newData.Mode, newData.UploadId, newData.ChunkSize, newData.TotalParts, newData.Status, newData.FinalizedFileId, newData.FinalizedAt, newData.ExpiresAt, newData.Id)
	return err
}

func (m *defaultUploadSessionsModel) tableName() string {
	return m.table
}
