/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseModal: typeof import('./../components/knowledge/modals/BaseModal.vue')['default']
    CommentPane: typeof import('./../components/knowledge/panels/CommentPane.vue')['default']
    CommentPanel: typeof import('./../components/knowledge/editor/CommentPanel.vue')['default']
    CreateBaseModal: typeof import('./../components/knowledge/modals/CreateBaseModal.vue')['default']
    CreateDocModal: typeof import('./../components/knowledge/modals/CreateDocModal.vue')['default']
    DeleteDocConfirm: typeof import('./../components/knowledge/modals/DeleteDocConfirm.vue')['default']
    DocumentContextMenu: typeof import('./../components/knowledge/components/DocumentContextMenu.vue')['default']
    DocumentMentionList: typeof import('./../components/knowledge/editor/DocumentMentionList.vue')['default']
    DocumentTree: typeof import('./../components/knowledge/DocumentTree.vue')['default']
    DocumentTreeNode: typeof import('./../components/knowledge/DocumentTreeNode.vue')['default']
    EditorCore: typeof import('./../components/knowledge/editor/EditorCore.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    EmbeddedDoc: typeof import('./../components/knowledge/components/EmbeddedDoc.vue')['default']
    ExportModal: typeof import('./../components/knowledge/modals/ExportModal.vue')['default']
    FormatToolbar: typeof import('./../components/knowledge/editor/FormatToolbar.vue')['default']
    KnowledgeEditorContainer: typeof import('./../components/knowledge/KnowledgeEditorContainer.vue')['default']
    KnowledgeMembers: typeof import('./../components/knowledge/KnowledgeMembers.vue')['default']
    KnowledgeSettings: typeof import('./../components/knowledge/KnowledgeSettings.vue')['default']
    KnowledgeSidebar: typeof import('./../components/knowledge/KnowledgeSidebar.vue')['default']
    KnowledgeStats: typeof import('./../components/knowledge/KnowledgeStats.vue')['default']
    MoveDocModal: typeof import('./../components/knowledge/modals/MoveDocModal.vue')['default']
    MoveTreeNode: typeof import('./../components/knowledge/modals/MoveTreeNode.vue')['default']
    OutlineItem: typeof import('./../components/knowledge/OutlineItem.vue')['default']
    PomodoroTimer: typeof import('./../components/common/PomodoroTimer.vue')['default']
    RenameDocModal: typeof import('./../components/knowledge/modals/RenameDocModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveVersionModal: typeof import('./../components/knowledge/modals/SaveVersionModal.vue')['default']
    SelectionCommentPopup: typeof import('./../components/knowledge/editor/SelectionCommentPopup.vue')['default']
    ShareModal: typeof import('./../components/knowledge/modals/ShareModal.vue')['default']
    Sidebar: typeof import('./../components/knowledge/Sidebar.vue')['default']
    SideNav: typeof import('./../components/home/SideNav.vue')['default']
    SlashCommandList: typeof import('./../components/knowledge/editor/SlashCommandList.vue')['default']
    TagInput: typeof import('./../components/knowledge/TagInput.vue')['default']
    TeamSwitcher: typeof import('./../components/common/TeamSwitcher.vue')['default']
    TimelineSection: typeof import('./../components/home/TimelineSection.vue')['default']
    TodayStatus: typeof import('./../components/home/TodayStatus.vue')['default']
    TopBar: typeof import('./../components/knowledge/TopBar.vue')['default']
    TreeNode: typeof import('./../components/knowledge/TreeNode.vue')['default']
    VersionHistoryModal: typeof import('./../components/knowledge/modals/VersionHistoryModal.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
